// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Subscription is an autogenerated mock type for the Subscription type
type Subscription struct {
	mock.Mock
}

type Subscription_Expecter struct {
	mock *mock.Mock
}

func (_m *Subscription) EXPECT() *Subscription_Expecter {
	return &Subscription_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with no fields
func (_m *Subscription) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Subscription_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type Subscription_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *Subscription_Expecter) ID() *Subscription_ID_Call {
	return &Subscription_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *Subscription_ID_Call) Run(run func()) *Subscription_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Subscription_ID_Call) Return(_a0 string) *Subscription_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Subscription_ID_Call) RunAndReturn(run func() string) *Subscription_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with no fields
func (_m *Subscription) Unsubscribe() {
	_m.Called()
}

// Subscription_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type Subscription_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
func (_e *Subscription_Expecter) Unsubscribe() *Subscription_Unsubscribe_Call {
	return &Subscription_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe")}
}

func (_c *Subscription_Unsubscribe_Call) Run(run func()) *Subscription_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Subscription_Unsubscribe_Call) Return() *Subscription_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *Subscription_Unsubscribe_Call) RunAndReturn(run func()) *Subscription_Unsubscribe_Call {
	_c.Run(run)
	return _c
}

// NewSubscription creates a new instance of Subscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscription(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Subscription {
	mock := &Subscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
