// Code generated by bubo-tool-gen. DO NOT EDIT.
// This file was generated for bubo:agentTool marker comments in the source code.

package main

import "github.com/casualjim/bubo/tool"

// Print account details for a user.
var printAccountDetailsTool = tool.Must(printAccountDetails, tool.Name("printAccountDetails"), tool.Description("Print account details for a user."), tool.Parameters("ctx"))
