// Code generated by bubo-tool-gen. DO NOT EDIT.
// This file was generated for bubo:agentTool marker comments in the source code.

package main

import "github.com/casualjim/bubo/tool"

// getWeather returns the weather for a location at a given time.
var getWeatherTool = tool.Must(getWeather, tool.Name("getWeather"), tool.Description("getWeather returns the weather for a location at a given time."), tool.Parameters("location", "date"))
