repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository
  name: bubo

  # Either `true` to enable automatically deleting head branches after pull requests are merged, or `false` to disable
  delete_branch_on_merge: true

  # Either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false` to prevent merging pull requests with merge commits
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: "#d73a4a"
    description: Something isn't working
  - name: enhancement
    color: "#a2eeef"
    description: New feature or request
