version: 2

project_name: bubo

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/bubo-tool-gen/main.go
    binary: bubo-tool-gen
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

# Git configuration
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "README"
      - Merge pull request
      - Merge branch

# GitHub release configuration
release:
  github:
    owner: casualjim
    name: bubo
  draft: false
  prerelease: auto
  mode: replace
  footer: |
    ## Installation
    ```sh
    go get github.com/casualjim/bubo/cmd/bubo-tool-gen@{{.Tag}}
    ```

git:
  tag_sort: "-version:refname"
