// Code generated by bubo-tool-gen. DO NOT EDIT.
// This file was generated for bubo:agentTool marker comments in the source code.

package main

import "github.com/casualjim/bubo/tool"

// Transfer spanish speaking users immediately
var transferToSpanishAgentTool = tool.Must(transferToSpanishAgent, tool.Name("transferToSpanishAgent"), tool.Description("Transfer spanish speaking users immediately"))
