// Code generated by bubo-tool-gen. DO NOT EDIT.
// This file was generated for bubo:agentTool marker comments in the source code.

package main

import "github.com/casualjim/bubo/tool"

// Refund an item. Refund an item. Make sure you have the item_id of the form item_... Ask for user confirmation before processing the refund.
var processRefundTool = tool.Must(processRefund, tool.Name("processRefund"), tool.Description("Refund an item. Refund an item. Make sure you have the item_id of the form item_... Ask for user confirmation before processing the refund."), tool.Parameters("itemID", "reason"))

// Apply a discount to the user's cart.
var applyDiscountTool = tool.Must(applyDiscount, tool.Name("applyDiscount"), tool.Description("Apply a discount to the user's cart."))

// Call this function if a user is asking about a topic that is not handled by the current agent.
var transferBackToTriageAgentTool = tool.Must(transferBackToTriageAgent, tool.Name("transferBackToTriageAgent"), tool.Description("Call this function if a user is asking about a topic that is not handled by the current agent."))

// Transfer the conversation to the sales agent.
var transferToSalesTool = tool.Must(transferToSales, tool.Name("transferToSales"), tool.Description("Transfer the conversation to the sales agent."))

// Transfer the conversation to the refunds agent.
var transferToRefundsTool = tool.Must(transferToRefunds, tool.Name("transferToRefunds"), tool.Description("Transfer the conversation to the refunds agent."))
