name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-unix:
    name: Test Unix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest

      - name: Initialize devenv
        run: devenv ci

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          cache: true

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Install gotestdox
        run: go install github.com/bitfield/gotestdox/cmd/gotestdox@latest

      - name: Run tests
        run: gotestsum -f testdox --format-hide-empty-pkg -- -race ./...
