name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          cache: true

      - name: Install NATS (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/nats-io/nats-server/releases/download/v2.10.24/nats-server-v2.10.24-windows-amd64.zip" -OutFile "nats.zip"
          Expand-Archive -Path "nats.zip" -DestinationPath "C:\nats"
          sc.exe create nats-server binPath="C:\nats\nats-server-v2.10.24-windows-amd64\nats-server.exe --log C:\nats\nats-server.log"
          sc.exe start nats-server
          Get-Content C:\nats\nats-server.log

      - name: Install NATS (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install nats-server
          brew services start nats-server

      - name: Install NATS (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          curl -L https://github.com/nats-io/nats-server/releases/download/v2.10.24/nats-server-v2.10.24-linux-amd64.tar.gz -o nats.tar.gz
          tar xzf nats.tar.gz
          sudo cp nats-server-v2.10.24-linux-amd64/nats-server /usr/local/bin/
          nats-server &

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Install gotestdox
        run: go install github.com/bitfield/gotestdox/cmd/gotestdox@latest

      - name: Run tests
        run: gotestsum -f testdox --format-hide-empty-pkg -- -coverprofile="cover.out" -covermode=atomic -race ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: "cover.out"
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
