name: Nix CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nix-build:
    name: Nix Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run flake checks
        run: nix flake check -L --debug

      - name: Build package
        run: nix build .#

      - name: Run tests
        run: nix develop --command bash -c "gotestsum -f testdox --format-hide-empty-pkg -- -coverprofile='cover.out' -covermode=atomic -race ./..."

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: "cover.out"
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
